apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Check out my GitHub repo
        uses: https://github.com/cloudbees-io/checkout@v1
      - name: echo-env
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: env
      - name: print-context-vars
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo '${{ toJSON(cloudbees) }}'
      - name: print-context-vars-2
        uses: docker://golang:1.20.3-alpine3.17
        run: echo '${{ vars.prop1 }} asdf ${{ toJSON(vars) }}'