name: Build Go Project

on: push

jobs:
  log-chained-cmd:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "this-secret"
    steps:
      - name: chained-command-without-mask
        run: echo -n "$MY_NAME" ; echo "random-str"
      - name: mask-using-chained-command
        run: echo -n "::add-mask::$MY_NAME" ; echo "random-str"
      - name: echo after mask
        run: echo "$MY_NAME"
      - name: mask-using-chained-command-2
        run: echo "::add-mask::$MY_NAME" ; echo "random-str"
      - name: echo after mask
        run: echo "$MY_NAME"
