name: Build Go Project

on: push

jobs:
  log-chained-cmd:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "this-secret"
    steps:
      - name: chained-command-example-same-line
        run: echo -n "$MY_NAME" ; echo "Random-str"
      - name: chained-command-example-new-line
        run: echo "$MY_NAME" ; echo "Random-str" 

        # now i am trying to mask just first echo,
        # the stdout for below step would be "::add-mask::this-secretRandom-str"
      - name: mask-using-chained-command
        run: echo -n "::add-mask::$MY_NAME" ; echo "Random-str"

        # the stdout for below step would be "this-secretRandom-str"        
      - name: echo after mask-chained-command
        run: echo -n "$MY_NAME" ; echo "Random-str"
        
      - name: echo after mask
        run: echo "$MY_NAME"
        
        # now i am trying to mask just first echo, (this time echo comes in new line)
        # the stdout for below step would be "::add-mask::this-secret
        # Random-str"
      - name: mask-using-chained-command-2
        run: echo "::add-mask::$MY_NAME" ; echo "random-str"
      - name: echo after mask
        run: echo "$MY_NAME"



  multiline-echo:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "this-secret"
    steps:
      - name: multiline-echo
        run: echo -e "Line one\nLine two\nLine three" > filename.txt
      - name: cat file
        run: echo "$(cat filename.txt)"
      - name: mask
        run: echo "::add-mask::$(cat filename.txt)"
      - name: cat file
        run: echo "$(cat filename.txt)"
        
  secret-output:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "this-secret"
    steps:
      - name: mask
        run: echo "::add-mask::$MY_NAME"
      - name: output-put
        id: sets-a-secret
        run: echo "my-secret=$MY_NAME" >> "$GITHUB_OUTPUT"
      - name: output-get
        run: echo "secrert ${{steps.sets-a-secret.outputs.my-secret}}"
      - name: output-ls
        run: ls $GITHUB_OUTPUT
      - name: output-cat
        run: cat $GITHUB_OUTPUT
