name: Build Go Project

on: push

jobs:
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use Output from job1
        run: echo "Received message ${{ needs.job1.outputs.message }}"
  job1:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.step1.outputs.result }}
    steps:
      - id: step1
        run: echo "result=Job Output Data" >> $GITHUB_ENV
