name: Contains from Env Example

on:
  push:

jobs:
  contains-from-env:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: "prod-deploy"

    steps:
      - name: Show environment variable
        run: echo "MY_ENV_VAR is $MY_ENV_VAR"

      - name: Check if MY_ENV_VAR contains 'prod'
        run: |
          echo "Contains 'prod': ${{ contains(env.MY_ENV_VAR, 'prod') }}"
          OUTPUT=$(echo "Hello from shell!")
          echo "Shell Output: $OUTPUT"
          echo "contains ${{contains(env.OUTPUT, 'Hello')}}"
