name: Build Go Project

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: assign-secret-to-env
        run: echo "SEC_ENV=${{ secrets.SECRET }}" >> "$GITHUB_ENV"    
      - id: step1
        run: echo "test=${SEC_ENV}" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: output
        run: echo "${{needs.job1.outputs.output1}} world"
